/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:51:25 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol SBUIBiometricEventMonitorDelegate <NSObject>
@required
-(BOOL)biometricEventMonitorShouldRelockAfterBioUnlock:(id)arg1;

@end

